name: Fintech API Tests

on:
  push:
    branches: [ "main", "master" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug files (root)
        run: ls -R

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Check Node version
        run: node -v

      - name: Install dependencies
        run: npm install

      - name: Debug after install
        run: ls -R

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Check fintech-api folder
        run: ls fintech-api

      - name: Start API Server
        run: |
          node fintech-api/server.js &
          sleep 5

      - name: Run Tests
        run: npx playwright test

      - name: Debug files
        run: ls -R